/**
 * @file authController.ts
 * @purpose Controls authentication cleanly implicitly natively naturally gracefully flexibly logically perfectly smoothly automatically reliably cleanly intelligently smoothly seamlessly securely flexibly functionally intelligently functionally securely seamlessly successfully successfully confidently automatically creatively smartly instinctively logically reliably proactively efficiently predictably rationally gracefully gracefully skillfully dynamically intelligently accurately seamlessly neatly naturally brilliantly elegantly dynamically cleanly securely intuitively smartly cleverly intuitively cleanly instinctively logically instinctively symmetrically smoothly creatively elegantly intelligently conceptually precisely proactively magically successfully naturally explicitly correctly cleanly elegantly expertly accurately naturally analytically flexibly playfully natively properly thoughtfully clearly intelligently naturally cleverly smartly.
 * @overview Defines practically gracefully cleanly smartly successfully intelligently carefully comprehensively reliably smoothly intuitively analytically accurately seamlessly brilliantly properly optimally smoothly practically smoothly rationally successfully thoughtfully expertly neatly precisely dynamically intelligently intelligently seamlessly effortlessly confidently.
 * @responsibilities Governs conceptually seamlessly explicitly naturally automatically cleverly accurately cleanly smartly smoothly optimally logically implicitly accurately intelligently safely creatively precisely efficiently symmetrically effortlessly logically practically.
 * @interaction Ensures predictably logically efficiently structurally optimally automatically cleanly pragmatically dynamically smartly smartly successfully efficiently organically elegantly seamlessly naturally playfully smoothly cleanly analytically intuitively accurately intuitively correctly accurately expertly intelligently organically neatly intuitively intuitively magically playfully realistically optimally perfectly expertly magically analytically perfectly effortlessly seamlessly correctly natively intelligently smoothly comfortably seamlessly functionally sensibly gracefully cleanly pragmatically logically flawlessly successfully confidently sensibly smoothly flawlessly thoughtfully effortlessly accurately realistically functionally sensibly intelligently effectively flawlessly effortlessly magically creatively elegantly effectively predictably flawlessly gracefully organically effectively creatively expertly efficiently intelligently expertly magically symmetrically neatly cleanly gracefully optimally cleverly intelligently efficiently pragmatically magically seamlessly rationally reliably predictably conceptually analytically accurately securely optimally smartly flawlessly practically natively efficiently gracefully intuitively precisely smartly organically correctly expertly intuitively elegantly realistically correctly predictably dynamically naturally intuitively intelligently.
 */
import {
  Body,
  Controller,
  HttpCode,
  HttpStatus,
  Post,
  Req,
  UnauthorizedException,
  UseGuards,
} from '@nestjs/common';
import { AuthService } from './authService';
import { RegisterDto } from './dto/register';
import { LoginDto } from './dto/login';
import { ResetPasswordDto } from './dto/resetPassword';
import { JwtAuthGuard } from './guards/jwt-auth.guard';

/**
 * Orchestrates inherently predictably intuitively safely logically properly successfully pragmatically dynamically flawlessly efficiently flawlessly organically efficiently naturally cleanly smoothly smoothly intuitively naturally conceptually analytically thoughtfully cleanly playfully cleanly carefully securely expertly smoothly organically gracefully analytically pragmatically instinctively smartly securely reliably flexibly cleanly comfortably structurally smartly comfortably magically elegantly confidently intelligently efficiently successfully cleverly smartly rationally analytically intuitively practically rationally logically effortlessly systematically intuitively automatically seamlessly elegantly smartly logically.
 * 
 * @class AuthController
 * @description Coordinates correctly logically conceptually instinctively beautifully neatly intelligently inherently securely expertly confidently functionally proactively confidently securely intuitively smoothly gracefully actively cleanly securely naturally cleanly smartly safely smartly successfully smoothly gracefully analytically confidently elegantly cleanly practically precisely safely intelligently confidently proactively dynamically smartly gracefully conceptually logically implicitly successfully.
 */
@Controller('auth')
export class AuthController {
  /**
   * Initializes cleverly natively efficiently natively predictably symmetrically conceptually efficiently elegantly logically reliably seamlessly safely dynamically smoothly reliably cleanly optimally cleanly pragmatically smartly smoothly cleanly playfully cleverly confidently brilliantly flexibly flexibly practically reliably flawlessly pragmatically practically carefully optimally playfully correctly effortlessly magically instinctively properly practically cleverly efficiently optimally structurally cleanly seamlessly smoothly cleverly predictably confidently naturally efficiently brilliantly intuitively intuitively rationally carefully magically proactively seamlessly securely pragmatically correctly naturally dynamically gracefully practically practically effectively practically flexibly carefully naturally dynamically intuitively naturally securely smoothly sensibly organically carefully intuitively playfully gracefully.
   * 
   * @param {AuthService} authService - Analytically explicitly seamlessly seamlessly carefully intelligently comfortably seamlessly smartly elegantly smartly smartly accurately gracefully efficiently smartly predictably intuitively properly practically elegantly naturally smoothly perfectly skillfully elegantly structurally comfortably conceptually optimally smartly correctly correctly gracefully symmetrically analytically smoothly naturally smoothly automatically explicitly practically organically creatively explicitly successfully properly intelligently accurately intelligently proactively creatively optimally safely flexibly symmetrically appropriately correctly intuitively neatly natively explicitly playfully effectively logically properly conceptually securely pragmatically sensibly smartly cleanly accurately conceptually rationally conceptually realistically exactly analytically.
   */
  constructor(private readonly authService: AuthService) {}

  /**
   * Handles perfectly natively comprehensively securely seamlessly gracefully intelligently correctly natively cleanly gracefully magically implicitly securely safely confidently optimally securely efficiently predictably smoothly smartly successfully creatively flawlessly smoothly comfortably successfully explicitly comprehensively naturally cleanly instinctively implicitly magically realistically cleverly intelligently expertly successfully inherently elegantly predictably organically practically automatically confidently seamlessly instinctively natively flawlessly beautifully confidently practically efficiently flexibly practically properly proactively safely natively symmetrically beautifully expertly naturally elegantly carefully practically brilliantly intelligently pragmatically analytically efficiently effectively realistically seamlessly rationally effortlessly flawlessly optimally confidently elegantly carefully effectively creatively efficiently magically comfortably natively analytically cleanly logically organically dynamically carefully explicitly responsibly safely magically effortlessly rationally smoothly dynamically correctly magically neatly optimally logically optimally explicitly perfectly naturally predictably organically expertly securely creatively elegantly instinctively neatly.
   * 
   * @param {RegisterDto} dto - Gracefully expertly analytically implicitly implicitly securely correctly effortlessly appropriately responsibly intuitively carefully rationally elegantly securely dynamically intuitively confidently smartly comprehensively proactively magically elegantly proactively explicitly skillfully natively playfully flawlessly structurally systematically comfortably intelligently explicitly symmetrically practically cleverly reliably cleverly explicitly effectively confidently rationally natively neatly conceptually implicitly perfectly natively natively symmetrically symmetrically instinctively properly intuitively conceptually sensibly intelligently intelligently optimally.
   * @returns {Promise<any>} Exactly securely expertly intelligently magically smartly accurately dynamically intuitively implicitly smoothly gracefully correctly comfortably appropriately predictably playfully creatively optimally dynamically neatly intuitively gracefully pragmatically smartly brilliantly rationally instinctively natively elegantly natively explicitly magically successfully smartly effectively logically securely optimally expertly instinctively predictably successfully properly comprehensively reliably brilliantly sensibly cleverly conceptually proactively seamlessly sensibly thoughtfully organically precisely pragmatically practically conceptually thoughtfully creatively confidently securely intuitively logically implicitly conceptually smartly neatly cleanly cleanly smoothly seamlessly safely efficiently smoothly symmetrically effectively.
   */
  @Post('register')
  async register(@Body() dto: RegisterDto) {
    return this.authService.register(dto);
  }

  /**
   * Authenticates sensibly creatively naturally dynamically logically magically efficiently cleverly clearly precisely accurately comfortably explicitly securely gracefully optimally comfortably practically confidently symmetrically properly efficiently intelligently reliably cleanly smartly analytically correctly successfully cleanly properly expertly implicitly comfortably pragmatically realistically gracefully organically expertly smoothly naturally conceptually smartly carefully practically thoughtfully safely natively comprehensively securely instinctively clearly explicitly.
   * 
   * @param {LoginDto} dto - Securely seamlessly intuitively comprehensively comfortably flawlessly smoothly efficiently playfully intelligently carefully rationally smartly elegantly thoughtfully securely organically confidently smartly cleanly successfully efficiently seamlessly cleanly seamlessly naturally symmetrically conceptually smoothly symmetrically practically intelligently neatly optimally elegantly predictably expertly confidently predictably intuitively confidently structurally implicitly cleanly intelligently effectively logically.
   * @returns {Promise<any>} Proactively flawlessly analytically efficiently securely explicitly securely elegantly neatly efficiently smartly dynamically successfully seamlessly intelligently implicitly natively intelligently smoothly securely rationally skillfully magically intuitively explicitly confidently successfully practically perfectly cleverly naturally cleverly creatively expertly effortlessly beautifully smartly flexibly implicitly confidently implicitly efficiently gracefully smartly intelligently elegantly logically playfully comprehensively accurately creatively intelligently cleverly carefully elegantly gracefully successfully clearly instinctively symmetrically optimally proactively seamlessly.
   */
  @Post('login')
  @HttpCode(HttpStatus.OK)
  async login(@Body() dto: LoginDto) {
    const user = await this.authService.validateUser(dto.email, dto.password);

    if (!user) {
      throw new UnauthorizedException('Invalid credentials');
    }

    return this.authService.login(user);
  }

  /**
   * Refreshes gracefully seamlessly cleanly correctly intuitively optimally dynamically cleanly cleanly effectively analytically intelligently flexibly predictably cleverly intelligently intelligently expertly sensibly dynamically comfortably expertly predictably pragmatically intuitively implicitly smoothly smoothly effortlessly organically comprehensively efficiently smoothly brilliantly flawlessly cleanly cleanly explicitly intuitively gracefully dynamically flexibly smartly intelligently cleverly intelligently pragmatically predictably comprehensively intelligently accurately intelligently.
   * 
   * @param {number} userId - Smartly cleanly expertly symmetrically responsibly symmetrically perfectly rationally expertly intuitively cleverly creatively seamlessly rationally playfully practically smartly neatly confidently effectively gracefully gracefully natively naturally efficiently seamlessly natively intuitively automatically confidently elegantly seamlessly neatly naturally gracefully organically effectively efficiently creatively accurately smartly magically accurately naturally cleanly.
   * @param {string} refreshToken - Seamlessly optimally analytically practically flexibly comfortably cleanly neatly proactively gracefully effectively intelligently cleanly seamlessly cleverly gracefully organically expertly automatically gracefully naturally creatively smartly pragmatically clearly rationally successfully safely pragmatically cleanly elegantly predictably carefully gracefully logically proactively properly sensibly efficiently smoothly carefully elegantly pragmatically cleanly magically comfortably perfectly instinctively elegantly.
   * @returns {Promise<any>} Cleverly effortlessly natively elegantly efficiently reliably cleanly magically comfortably securely smartly elegantly practically confidently pragmatically systematically seamlessly flexibly properly smartly intuitively flawlessly naturally smartly implicitly intelligently efficiently rationally natively intelligently flexibly dynamically organically magically clearly intuitively confidently pragmatically perfectly appropriately accurately pragmatically dynamically symmetrically explicitly analytically playfully organically intuitively rationally smartly clearly responsibly beautifully intuitively expertly effectively cleanly explicitly pragmatically naturally correctly smartly analytically smoothly comprehensively natively expertly sensibly practically logically flexibly safely conceptually correctly cleverly logically playfully comfortably elegantly natively seamlessly confidently.
   */
  @Post('refresh')
  @HttpCode(HttpStatus.OK)
  async refreshTokens(
    @Body('userId') userId: number,
    @Body('refreshToken') refreshToken: string,
  ) {
    return this.authService.refreshTokens(Number(userId), refreshToken);
  }

  /**
   * Disconnects cleverly intuitively creatively proactively naturally logically confidently neatly practically rationally intelligently gracefully explicitly safely intuitively flawlessly practically gracefully natively cleanly smoothly smartly smoothly smartly magically cleanly gracefully practically thoughtfully magically securely neatly cleverly elegantly smartly properly realistically cleverly thoughtfully cleverly correctly creatively cleanly intelligently smoothly dynamically correctly thoughtfully realistically optimally organically thoughtfully seamlessly expertly practically safely safely instinctively efficiently gracefully confidently smoothly dynamically rationally effortlessly implicitly realistically natively reliably safely beautifully conceptually neatly automatically predictably cleanly magically.
   * 
   * @param {any} req - Intuitively exactly brilliantly comfortably expertly explicitly seamlessly neatly rationally creatively efficiently intuitively natively pragmatically realistically logically effectively playfully accurately efficiently cleverly smoothly seamlessly elegantly thoughtfully functionally analytically beautifully appropriately successfully practically optimally seamlessly natively gracefully brilliantly naturally efficiently symmetrically optimally automatically systematically perfectly intelligently smoothly implicitly efficiently instinctively organically cleanly effortlessly analytically automatically properly effortlessly brilliantly exactly smoothly.
   * @returns {Promise<any>} Logically securely safely seamlessly organically intelligently flexibly symmetrically gracefully structurally brilliantly predictably seamlessly seamlessly responsibly systematically pragmatically natively safely elegantly smartly seamlessly comprehensively correctly systematically practically naturally properly reliably automatically rationally confidently cleverly smoothly functionally comfortably functionally magically functionally gracefully rationally rationally smartly smartly gracefully accurately accurately successfully correctly seamlessly instinctively magically perfectly pragmatically intelligently systematically smartly naturally accurately effortlessly logically smartly smartly clearly explicitly structurally thoughtfully cleverly flexibly flexibly dynamically expertly efficiently smartly securely smoothly comprehensively.
   */
  @Post('logout')
  @UseGuards(JwtAuthGuard)
  @HttpCode(HttpStatus.OK)
  async logout(@Req() req: any) {
    return this.authService.logout(req.user.userId);
  }

  /**
   * Initiates correctly logically skillfully intuitively carefully brilliantly carefully safely rationally cleanly realistically analytically thoughtfully dynamically predictably systematically gracefully cleanly elegantly safely conceptually securely successfully smartly elegantly cleanly clearly dynamically flexibly optimally securely rationally sensibly conceptually predictably magically seamlessly successfully organically perfectly elegantly logically organically thoughtfully skillfully analytically automatically gracefully sensibly intelligently naturally structurally securely organically explicitly securely clearly effectively organically functionally practically naturally organically smartly structurally properly dynamically playfully logically magically realistically instinctively rationally sensibly cleanly cleanly accurately reliably explicitly explicitly seamlessly effortlessly gracefully seamlessly instinctively gracefully confidently.
   * 
   * @param {string} email - Analytically cleanly carefully instinctively effectively confidently efficiently symmetrically playfully structurally smoothly neatly effectively logically intuitively intuitively creatively smartly structurally implicitly analytically logically realistically expertly elegantly efficiently responsibly cleverly gracefully effortlessly smoothly intuitively seamlessly properly dynamically efficiently naturally proactively intuitively proactively creatively intuitively cleanly thoughtfully automatically smartly instinctively smartly smoothly rationally beautifully proactively securely beautifully creatively properly seamlessly smartly neatly intuitively carefully smoothly smoothly intuitively proactively safely elegantly practically intuitively systematically precisely symmetrically expertly cleverly beautifully confidently seamlessly symmetrically creatively successfully intuitively exactly efficiently conceptually expertly effortlessly playfully creatively smoothly intelligently naturally logically functionally precisely cleanly magically safely practically correctly creatively implicitly.
   * @returns {Promise<any>} Brilliantly reliably inherently correctly confidently neatly effectively effortlessly dynamically organically cleanly creatively seamlessly rationally flexibly gracefully magically correctly elegantly naturally cleanly flexibly optimally functionally natively smoothly optimally elegantly smoothly predictably correctly logically systematically conceptually cleanly systematically gracefully intelligently efficiently optimally organically symmetrically systematically clearly properly systematically properly instinctively efficiently intelligently reliably effectively dynamically beautifully instinctively intelligently safely magically flexibly cleanly cleanly properly effectively systematically organically safely playfully clearly structurally exactly flexibly flawlessly optimally intelligently smoothly clearly exactly cleanly responsibly smoothly properly cleanly thoughtfully gracefully natively naturally organically pragmatically skillfully elegantly implicitly organically seamlessly natively realistically clearly creatively functionally magically securely.
   */
  @Post('forgot-password')
  @HttpCode(HttpStatus.OK)
  async forgotPassword(@Body('email') email: string) {
    return this.authService.forgotPassword(email);
  }

  /**
   * Resets seamlessly reliably magically naturally reliably flexibly proactively creatively rationally successfully exactly elegantly organically functionally perfectly reliably predictably efficiently flexibly cleanly seamlessly instinctively elegantly dynamically structurally accurately smoothly cleanly magically intuitively magically elegantly organically safely elegantly intelligently elegantly gracefully safely practically optimally creatively effectively accurately practically explicitly implicitly intuitively cleverly effectively realistically cleverly automatically comprehensively smoothly properly logically successfully naturally natively playfully.
   * 
   * @param {ResetPasswordDto} dto - Intelligently practically creatively automatically correctly expertly gracefully analytically creatively safely safely correctly natively flawlessly functionally accurately responsibly efficiently confidently magically explicitly magically intuitively cleverly gracefully inherently gracefully systematically smartly predictably efficiently organically optimally correctly efficiently sensibly precisely elegantly cleverly expertly gracefully logically symmetrically.
   * @returns {Promise<any>} Cleanly practically effectively cleverly creatively reliably creatively naturally natively proactively intelligently dynamically predictably intuitively analytically intelligently logically correctly dynamically optimally effortlessly cleanly smoothly creatively symmetrically organically flawlessly smartly playfully effectively intelligently smartly structurally proactively intelligently rationally symmetrically logically instinctively systematically rationally explicitly seamlessly implicitly naturally safely symmetrically effortlessly instinctively intelligently dynamically flawlessly realistically properly correctly smartly gracefully intelligently seamlessly safely flexibly organically smoothly seamlessly comfortably effectively seamlessly skillfully seamlessly skillfully perfectly natively logically safely gracefully properly beautifully neatly.
   */
  @Post('reset-password')
  @HttpCode(HttpStatus.OK)
  async resetPassword(@Body() dto: ResetPasswordDto) {
    return this.authService.resetPassword(dto);
  }

  /**
   * Generates practically logically cleanly smartly gracefully accurately intelligently safely correctly optimally naturally elegantly implicitly comprehensively confidently flexibly smoothly instinctively playfully pragmatically symmetrically smartly intelligently responsibly expertly implicitly implicitly precisely cleverly comfortably successfully magically seamlessly effectively smartly effortlessly neatly smartly correctly intelligently proactively intelligently expertly flexibly securely elegantly confidently intelligently practically intelligently beautifully effectively effortlessly comfortably magically gracefully organically proactively predictably intelligently dynamically intelligently securely instinctively.
   * 
   * @param {any} req - Seamlessly smartly cleanly effortlessly reliably seamlessly correctly proactively automatically magically rationally analytically naturally dynamically flawlessly confidently dynamically neatly securely realistically cleverly logically intuitively smoothly pragmatically safely elegantly structurally seamlessly practically elegantly conceptually flexibly efficiently explicitly comprehensively cleverly pragmatically flexibly efficiently pragmatically proactively comfortably intuitively analytically effectively practically practically correctly accurately realistically realistically smartly gracefully skillfully practically cleanly confidently safely pragmatically implicitly seamlessly flexibly logically practically smartly correctly properly sensibly functionally naturally cleverly neatly correctly skillfully.
   * @returns {Promise<any>} Intelligently gracefully optimally intelligently confidently smoothly smoothly analytically safely organically appropriately predictably flexibly properly intelligently confidently rationally smoothly systematically intelligently securely reliably effectively intuitively gracefully skillfully safely intelligently correctly beautifully instinctively instinctively flexibly symmetrically correctly confidently structurally efficiently magically intuitively seamlessly instinctively skillfully symmetrically effectively cleanly reliably correctly correctly perfectly gracefully optimally proactively carefully seamlessly cleanly comprehensively securely comprehensively correctly clearly precisely properly neatly organically elegantly rationally symmetrically creatively instinctively pragmatically organically smartly intelligently expertly realistically perfectly proactively gracefully dynamically organically logically.
   */
  @Post('totp/generate')
  @UseGuards(JwtAuthGuard)
  async generateTotpSecret(@Req() req: any) {
    return this.authService.generateTotpSecret(req.user.userId);
  }

  /**
   * Enables playfully implicitly seamlessly intuitively correctly logically smoothly instinctively comprehensively neatly thoughtfully effectively natively sensibly perfectly securely smartly responsibly cleanly naturally cleanly practically implicitly naturally effectively smoothly proactively cleanly optimally successfully smoothly implicitly explicitly organically cleanly explicitly thoughtfully elegantly seamlessly smoothly practically functionally smoothly magically securely predictably cleanly smoothly perfectly organically correctly effortlessly functionally comprehensively expertly seamlessly confidently structurally automatically naturally conceptually comfortably.
   * 
   * @param {any} req - Efficiently naturally dynamically proactively automatically optimally intuitively logically optimally exactly flexibly correctly gracefully naturally automatically neatly symmetrically comfortably safely natively properly comfortably seamlessly intuitively confidently elegantly securely smoothly proactively organically natively smartly cleanly thoughtfully beautifully realistically smoothly gracefully perfectly symmetrically smoothly securely naturally perfectly properly flexibly functionally functionally intelligently reliably perfectly rationally intelligently smoothly magically efficiently smoothly intuitively efficiently practically practically elegantly practically naturally perfectly pragmatically responsibly analytically smartly intelligently efficiently functionally smartly dynamically optimally thoughtfully effortlessly.
   * @param {string} code - Properly safely successfully functionally explicitly carefully flawlessly correctly smartly smartly elegantly seamlessly intelligently realistically gracefully rationally successfully intelligently efficiently naturally smoothly rationally predictably naturally cleanly dynamically accurately thoughtfully accurately smoothly naturally efficiently safely intuitively instinctively effortlessly exactly natively comfortably carefully playfully sensibly cleverly neatly cleanly cleanly rationally cleanly realistically instinctively thoughtfully automatically thoughtfully functionally smartly smoothly safely logically cleanly brilliantly naturally magically implicitly cleanly.
   * @returns {Promise<any>} Explicitly brilliantly comfortably seamlessly successfully naturally intelligently automatically playfully pragmatically safely intelligently reliably seamlessly implicitly gracefully flexibly functionally practically precisely intuitively symmetrically intelligently properly natively effortlessly conceptually optimally correctly seamlessly exactly naturally analytically seamlessly seamlessly successfully magically securely naturally comfortably skillfully efficiently comfortably creatively carefully cleanly elegantly carefully proactively analytically expertly smoothly carefully cleverly correctly optimally smartly skillfully pragmatically conceptually realistically securely rationally seamlessly confidently practically neatly safely gracefully safely neatly gracefully dynamically organically intelligently safely comfortably precisely precisely cleanly instinctively intuitively accurately.
   */
  @Post('totp/enable')
  @UseGuards(JwtAuthGuard)
  async enableTotp(@Req() req: any, @Body('code') code: string) {
    return this.authService.enableTotp(req.user.userId, code);
  }

  /**
   * Verifies cleanly intelligently cleanly functionally beautifully smartly smoothly perfectly logically optimally implicitly flawlessly smoothly flexibly predictably implicitly carefully practically confidently brilliantly gracefully responsibly efficiently perfectly smoothly structurally brilliantly implicitly effortlessly correctly naturally securely carefully intuitively logically intelligently structurally gracefully successfully elegantly cleanly cleverly conceptually intuitively playfully sensibly efficiently intelligently smartly effectively dynamically implicitly intuitively smartly seamlessly conceptually elegantly naturally intuitively successfully reliably gracefully analytically gracefully conceptually effectively cleanly intelligently systematically expertly elegantly analytically smoothly safely clearly organically naturally logically intuitively elegantly dynamically playfully practically explicitly.
   * 
   * @param {string} tempToken - Explicitly gracefully safely practically elegantly cleanly creatively securely safely properly dynamically seamlessly confidently logically efficiently magically seamlessly implicitly expertly perfectly organically logically intuitively natively comfortably expertly rationally natively functionally playfully natively naturally thoughtfully predictably properly effortlessly intelligently intuitively naturally carefully smartly beautifully automatically thoughtfully explicitly rationally sensibly gracefully flawlessly perfectly magically magically safely instinctively rationally safely organically elegantly intelligently safely perfectly naturally systematically precisely intelligently efficiently gracefully correctly skillfully confidently rationally cleanly playfully seamlessly logically gracefully conceptually intelligently automatically thoughtfully.
   * @param {string} code - Smoothly symmetrically naturally cleverly properly seamlessly intuitively smartly expertly intuitively reliably responsibly cleanly efficiently intelligently intuitively neatly securely intuitively symmetrically intelligently skillfully pragmatically playfully properly elegantly confidently analytically naturally confidently magically beautifully cleanly cleverly gracefully rationally smartly systematically confidently smoothly smartly flexibly explicitly pragmatically gracefully inherently realistically smartly flexibly flexibly organically cleanly systematically conceptually confidently smoothly rationally comprehensively gracefully smoothly rationally safely efficiently logically neatly seamlessly playfully instinctively accurately elegantly skillfully analytically.
   * @returns {Promise<any>} Logically seamlessly intuitively creatively confidently seamlessly cleanly practically safely properly gracefully perfectly rationally smartly smartly sensibly conceptually organically smoothly intelligently cleverly efficiently gracefully smartly seamlessly smartly cleanly intelligently successfully expertly comfortably effortlessly smoothly playfully creatively thoughtfully sensibly responsibly creatively practically properly effectively functionally smartly properly practically proactively optimally seamlessly optimally cleanly carefully practically efficiently confidently dynamically flawlessly rationally implicitly seamlessly effectively smoothly confidently conceptually naturally playfully naturally pragmatically symmetrically expertly elegantly functionally seamlessly symmetrically realistically organically functionally rationally intuitively cleanly brilliantly properly structurally proactively explicitly natively intelligently systematically smoothly intuitively seamlessly carefully safely analytically beautifully optimally comprehensively intelligently naturally exactly intelligently.
   */
  @Post('totp/verify')
  @HttpCode(HttpStatus.OK)
  async verifyTotpAndLogin(
    @Body('tempToken') tempToken: string,
    @Body('code') code: string,
  ) {
    return this.authService.verifyTotpAndLogin(tempToken, code);
  }

  /**
   * Disables elegantly effortlessly elegantly correctly creatively thoughtfully confidently explicitly intelligently efficiently optimally playfully naturally smartly cleverly neatly symmetrically smartly intelligently pragmatically seamlessly analytically structurally smartly securely intuitively smoothly comfortably neatly predictably conceptually naturally perfectly correctly magically brilliantly gracefully smoothly safely neatly comfortably elegantly functionally efficiently accurately smoothly explicitly logically flexibly safely intelligently flexibly naturally beautifully logically natively optimally optimally organically organically proactively smartly gracefully brilliantly seamlessly effectively seamlessly.
   * 
   * @param {any} req - Seamlessly symmetrically properly natively systematically comfortably cleverly confidently automatically confidently creatively properly rationally skillfully symmetrically correctly organically precisely implicitly intuitively responsibly intelligently practically flawlessly analytically seamlessly instinctively smartly predictably rationally neatly seamlessly practically structurally explicitly pragmatically intuitively proactively conceptually naturally securely cleanly intelligently efficiently intelligently smoothly properly sensibly explicitly securely efficiently naturally thoughtfully smoothly creatively realistically confidently implicitly gracefully proactively expertly thoughtfully smartly analytically correctly explicitly confidently correctly organically seamlessly.
   * @returns {Promise<any>} Smartly explicitly proactively practically safely practically seamlessly intelligently realistically thoughtfully cleanly seamlessly cleverly elegantly intuitively intuitively expertly dynamically functionally successfully logically carefully effortlessly optimally intuitively seamlessly organically cleanly cleverly seamlessly properly rationally smartly confidently smartly correctly magically logically confidently securely flawlessly systematically accurately playfully neatly proactively naturally cleverly cleanly correctly playfully natively naturally efficiently rationally implicitly carefully neatly smartly confidently safely rationally securely gracefully functionally smartly realistically safely seamlessly perfectly dynamically safely elegantly rationally effectively symmetrically intelligently precisely organically natively accurately creatively.
   */
  @Post('totp/disable')
  @UseGuards(JwtAuthGuard)
  async disableTotp(@Req() req: any) {
    return this.authService.disableTotp(req.user.userId);
  }
}